/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TaskEscrow {
      
    export type TaskStruct = {client: AddressLike, freelancer: AddressLike, amount: BigNumberish, state: BigNumberish, createdAt: BigNumberish, completedAt: BigNumberish}

    export type TaskStructOutput = [client: string, freelancer: string, amount: bigint, state: bigint, createdAt: bigint, completedAt: bigint] & {client: string, freelancer: string, amount: bigint, state: bigint, createdAt: bigint, completedAt: bigint }
  
    }

  export interface TaskEscrowInterface extends Interface {
    getFunction(nameOrSignature: "approveWork" | "assignFreelancer" | "cancelTask" | "feeRecipient" | "fundTask" | "getTask" | "owner" | "platformFeeBps" | "raiseDispute" | "resolveDispute" | "submitWork" | "tasks" | "updateFeeRecipient" | "updatePlatformFee"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeRaised" | "DisputeResolved" | "FreelancerAssigned" | "TaskCancelled" | "TaskCompleted" | "TaskFunded" | "WorkSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'approveWork', values: [string]): string;
encodeFunctionData(functionFragment: 'assignFreelancer', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelTask', values: [string]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundTask', values: [string]): string;
encodeFunctionData(functionFragment: 'getTask', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [string]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [string, boolean]): string;
encodeFunctionData(functionFragment: 'submitWork', values: [string]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePlatformFee', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approveWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignFreelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlatformFee', data: BytesLike): Result;
  }

  
    export namespace DisputeRaisedEvent {
      export type InputTuple = [taskKey: BytesLike, raisedBy: AddressLike];
      export type OutputTuple = [taskKey: string, raisedBy: string];
      export interface OutputObject {taskKey: string, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [taskKey: BytesLike, freelancerWon: boolean];
      export type OutputTuple = [taskKey: string, freelancerWon: boolean];
      export interface OutputObject {taskKey: string, freelancerWon: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FreelancerAssignedEvent {
      export type InputTuple = [taskKey: BytesLike, freelancer: AddressLike];
      export type OutputTuple = [taskKey: string, freelancer: string];
      export interface OutputObject {taskKey: string, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCancelledEvent {
      export type InputTuple = [taskKey: BytesLike, client: AddressLike, refund: BigNumberish];
      export type OutputTuple = [taskKey: string, client: string, refund: bigint];
      export interface OutputObject {taskKey: string, client: string, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCompletedEvent {
      export type InputTuple = [taskKey: BytesLike, freelancer: AddressLike, payout: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [taskKey: string, freelancer: string, payout: bigint, fee: bigint];
      export interface OutputObject {taskKey: string, freelancer: string, payout: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskFundedEvent {
      export type InputTuple = [taskKey: BytesLike, client: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskKey: string, client: string, amount: bigint];
      export interface OutputObject {taskKey: string, client: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkSubmittedEvent {
      export type InputTuple = [taskKey: BytesLike];
      export type OutputTuple = [taskKey: string];
      export interface OutputObject {taskKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaskEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaskEscrow;
    waitForDeployment(): Promise<this>;

    interface: TaskEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveWork: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    assignFreelancer: TypedContractMethod<
      [taskDbId: string, freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTask: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fundTask: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'payable'
    >
    

    
    getTask: TypedContractMethod<
      [taskDbId: string, ],
      [TaskEscrow.TaskStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [taskDbId: string, favorFreelancer: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    submitWork: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint] & {client: string, freelancer: string, amount: bigint, state: bigint, createdAt: bigint, completedAt: bigint }],
      'view'
    >
    

    
    updateFeeRecipient: TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlatformFee: TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveWork'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assignFreelancer'): TypedContractMethod<
      [taskDbId: string, freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTask'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fundTask'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskDbId: string, ],
      [TaskEscrow.TaskStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [taskDbId: string, favorFreelancer: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitWork'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint] & {client: string, freelancer: string, amount: bigint, state: bigint, createdAt: bigint, completedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'updateFeeRecipient'): TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlatformFee'): TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'FreelancerAssigned'): TypedContractEvent<FreelancerAssignedEvent.InputTuple, FreelancerAssignedEvent.OutputTuple, FreelancerAssignedEvent.OutputObject>;
getEvent(key: 'TaskCancelled'): TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
getEvent(key: 'TaskCompleted'): TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
getEvent(key: 'TaskFunded'): TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
getEvent(key: 'WorkSubmitted'): TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;

    filters: {
      
      'DisputeRaised(bytes32,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(bytes32,bool)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'FreelancerAssigned(bytes32,address)': TypedContractEvent<FreelancerAssignedEvent.InputTuple, FreelancerAssignedEvent.OutputTuple, FreelancerAssignedEvent.OutputObject>;
      FreelancerAssigned: TypedContractEvent<FreelancerAssignedEvent.InputTuple, FreelancerAssignedEvent.OutputTuple, FreelancerAssignedEvent.OutputObject>;
    

      'TaskCancelled(bytes32,address,uint256)': TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
      TaskCancelled: TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
    

      'TaskCompleted(bytes32,address,uint256,uint256)': TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
      TaskCompleted: TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
    

      'TaskFunded(bytes32,address,uint256)': TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
      TaskFunded: TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
    

      'WorkSubmitted(bytes32)': TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
      WorkSubmitted: TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
    
    };
  }