/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TaskEscrowInterface extends Interface {
    getFunction(nameOrSignature: "MAX_FEE_BP" | "MAX_TASK_ID_LEN" | "approveWork" | "assignFreelancer" | "cancelTask" | "feeBasisPoints" | "feeRecipient" | "fundTask" | "getContractBalance" | "getTask" | "getTaskState" | "owner" | "pause" | "paused" | "pendingWithdrawals" | "raiseDispute" | "renounceOwnership" | "resolveDispute" | "setFeeBasisPoints" | "setFeeRecipient" | "submitWork" | "transferOwnership" | "unpause" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeRaised" | "DisputeResolved" | "FeeBasisPointsUpdated" | "FeeRecipientUpdated" | "FreelancerAssigned" | "OwnershipTransferred" | "Paused" | "TaskCancelled" | "TaskCompleted" | "TaskFunded" | "Unpaused" | "Withdrawn" | "WorkSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_FEE_BP', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_TASK_ID_LEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveWork', values: [string]): string;
encodeFunctionData(functionFragment: 'assignFreelancer', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelTask', values: [string]): string;
encodeFunctionData(functionFragment: 'feeBasisPoints', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundTask', values: [string]): string;
encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTask', values: [string]): string;
encodeFunctionData(functionFragment: 'getTaskState', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingWithdrawals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [string, boolean]): string;
encodeFunctionData(functionFragment: 'setFeeBasisPoints', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submitWork', values: [string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_FEE_BP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_TASK_ID_LEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignFreelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeBasisPoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTaskState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeBasisPoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DisputeRaisedEvent {
      export type InputTuple = [taskKey: BytesLike, raisedBy: AddressLike];
      export type OutputTuple = [taskKey: string, raisedBy: string];
      export interface OutputObject {taskKey: string, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [taskKey: BytesLike, favorFreelancer: boolean, resolvedBy: AddressLike];
      export type OutputTuple = [taskKey: string, favorFreelancer: boolean, resolvedBy: string];
      export interface OutputObject {taskKey: string, favorFreelancer: boolean, resolvedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeBasisPointsUpdatedEvent {
      export type InputTuple = [oldBp: BigNumberish, newBp: BigNumberish];
      export type OutputTuple = [oldBp: bigint, newBp: bigint];
      export interface OutputObject {oldBp: bigint, newBp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeRecipientUpdatedEvent {
      export type InputTuple = [oldRecipient: AddressLike, newRecipient: AddressLike];
      export type OutputTuple = [oldRecipient: string, newRecipient: string];
      export interface OutputObject {oldRecipient: string, newRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FreelancerAssignedEvent {
      export type InputTuple = [taskKey: BytesLike, client: AddressLike, freelancer: AddressLike];
      export type OutputTuple = [taskKey: string, client: string, freelancer: string];
      export interface OutputObject {taskKey: string, client: string, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCancelledEvent {
      export type InputTuple = [taskKey: BytesLike, client: AddressLike, refund: BigNumberish];
      export type OutputTuple = [taskKey: string, client: string, refund: bigint];
      export interface OutputObject {taskKey: string, client: string, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCompletedEvent {
      export type InputTuple = [taskKey: BytesLike, client: AddressLike, freelancer: AddressLike, freelancerPayout: BigNumberish, platformFee: BigNumberish];
      export type OutputTuple = [taskKey: string, client: string, freelancer: string, freelancerPayout: bigint, platformFee: bigint];
      export interface OutputObject {taskKey: string, client: string, freelancer: string, freelancerPayout: bigint, platformFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskFundedEvent {
      export type InputTuple = [taskKey: BytesLike, taskDbId: string, client: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskKey: string, taskDbId: string, client: string, amount: bigint];
      export interface OutputObject {taskKey: string, taskDbId: string, client: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkSubmittedEvent {
      export type InputTuple = [taskKey: BytesLike, freelancer: AddressLike];
      export type OutputTuple = [taskKey: string, freelancer: string];
      export interface OutputObject {taskKey: string, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaskEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaskEscrow;
    waitForDeployment(): Promise<this>;

    interface: TaskEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_FEE_BP: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_TASK_ID_LEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approveWork: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    assignFreelancer: TypedContractMethod<
      [taskDbId: string, freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTask: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    feeBasisPoints: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fundTask: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'payable'
    >
    

    
    getContractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTask: TypedContractMethod<
      [taskDbId: string, ],
      [[string, string, bigint, bigint, bigint, bigint] & {client: string, freelancer: string, amount: bigint, state: bigint, fundedAt: bigint, completedAt: bigint }],
      'view'
    >
    

    
    getTaskState: TypedContractMethod<
      [taskDbId: string, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingWithdrawals: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [taskDbId: string, favorFreelancer: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeBasisPoints: TypedContractMethod<
      [newBp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeRecipient: TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitWork: TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_FEE_BP'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_TASK_ID_LEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveWork'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assignFreelancer'): TypedContractMethod<
      [taskDbId: string, freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTask'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeBasisPoints'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fundTask'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getContractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskDbId: string, ],
      [[string, string, bigint, bigint, bigint, bigint] & {client: string, freelancer: string, amount: bigint, state: bigint, fundedAt: bigint, completedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTaskState'): TypedContractMethod<
      [taskDbId: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingWithdrawals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [taskDbId: string, favorFreelancer: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeBasisPoints'): TypedContractMethod<
      [newBp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRecipient'): TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitWork'): TypedContractMethod<
      [taskDbId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'FeeBasisPointsUpdated'): TypedContractEvent<FeeBasisPointsUpdatedEvent.InputTuple, FeeBasisPointsUpdatedEvent.OutputTuple, FeeBasisPointsUpdatedEvent.OutputObject>;
getEvent(key: 'FeeRecipientUpdated'): TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
getEvent(key: 'FreelancerAssigned'): TypedContractEvent<FreelancerAssignedEvent.InputTuple, FreelancerAssignedEvent.OutputTuple, FreelancerAssignedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'TaskCancelled'): TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
getEvent(key: 'TaskCompleted'): TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
getEvent(key: 'TaskFunded'): TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
getEvent(key: 'WorkSubmitted'): TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;

    filters: {
      
      'DisputeRaised(bytes32,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(bytes32,bool,address)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'FeeBasisPointsUpdated(uint16,uint16)': TypedContractEvent<FeeBasisPointsUpdatedEvent.InputTuple, FeeBasisPointsUpdatedEvent.OutputTuple, FeeBasisPointsUpdatedEvent.OutputObject>;
      FeeBasisPointsUpdated: TypedContractEvent<FeeBasisPointsUpdatedEvent.InputTuple, FeeBasisPointsUpdatedEvent.OutputTuple, FeeBasisPointsUpdatedEvent.OutputObject>;
    

      'FeeRecipientUpdated(address,address)': TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
      FeeRecipientUpdated: TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
    

      'FreelancerAssigned(bytes32,address,address)': TypedContractEvent<FreelancerAssignedEvent.InputTuple, FreelancerAssignedEvent.OutputTuple, FreelancerAssignedEvent.OutputObject>;
      FreelancerAssigned: TypedContractEvent<FreelancerAssignedEvent.InputTuple, FreelancerAssignedEvent.OutputTuple, FreelancerAssignedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'TaskCancelled(bytes32,address,uint256)': TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
      TaskCancelled: TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
    

      'TaskCompleted(bytes32,address,address,uint256,uint256)': TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
      TaskCompleted: TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
    

      'TaskFunded(bytes32,string,address,uint256)': TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
      TaskFunded: TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    

      'WorkSubmitted(bytes32,address)': TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
      WorkSubmitted: TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
    
    };
  }